//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineVacationReservation.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.CruiseSoap")]
    public interface CruiseSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/searchCruise", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet searchCruise(string Departing_Country, string Departing_City, string Destination_Country, string Destination_City, System.DateTime Date_CheckIn, System.DateTime Date_CheckOut);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/searchCruise", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> searchCruiseAsync(string Departing_Country, string Departing_City, string Destination_Country, string Destination_City, System.DateTime Date_CheckIn, System.DateTime Date_CheckOut);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CruiseSoapChannel : OnlineVacationReservation.ServiceReference1.CruiseSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CruiseSoapClient : System.ServiceModel.ClientBase<OnlineVacationReservation.ServiceReference1.CruiseSoap>, OnlineVacationReservation.ServiceReference1.CruiseSoap {
        
        public CruiseSoapClient() {
        }
        
        public CruiseSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CruiseSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CruiseSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CruiseSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet searchCruise(string Departing_Country, string Departing_City, string Destination_Country, string Destination_City, System.DateTime Date_CheckIn, System.DateTime Date_CheckOut) {
            return base.Channel.searchCruise(Departing_Country, Departing_City, Destination_Country, Destination_City, Date_CheckIn, Date_CheckOut);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> searchCruiseAsync(string Departing_Country, string Departing_City, string Destination_Country, string Destination_City, System.DateTime Date_CheckIn, System.DateTime Date_CheckOut) {
            return base.Channel.searchCruiseAsync(Departing_Country, Departing_City, Destination_Country, Destination_City, Date_CheckIn, Date_CheckOut);
        }
    }
}
