//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineVacationReservation.ServiceReference4 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference4.CruiseServiceSoap")]
    public interface CruiseServiceSoap {
        
        // CODEGEN: Generating message contract since element name FirstName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CruiseBooking", ReplyAction="*")]
        OnlineVacationReservation.ServiceReference4.CruiseBookingResponse CruiseBooking(OnlineVacationReservation.ServiceReference4.CruiseBookingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CruiseBooking", ReplyAction="*")]
        System.Threading.Tasks.Task<OnlineVacationReservation.ServiceReference4.CruiseBookingResponse> CruiseBookingAsync(OnlineVacationReservation.ServiceReference4.CruiseBookingRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CruiseBookingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CruiseBooking", Namespace="http://tempuri.org/", Order=0)]
        public OnlineVacationReservation.ServiceReference4.CruiseBookingRequestBody Body;
        
        public CruiseBookingRequest() {
        }
        
        public CruiseBookingRequest(OnlineVacationReservation.ServiceReference4.CruiseBookingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CruiseBookingRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FirstName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string LastName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Phone_Number;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Email;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int Cruise_ID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int Number_of_rooms;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Room;
        
        public CruiseBookingRequestBody() {
        }
        
        public CruiseBookingRequestBody(string FirstName, string LastName, string Phone_Number, string Email, int Cruise_ID, int Number_of_rooms, string Room) {
            this.FirstName = FirstName;
            this.LastName = LastName;
            this.Phone_Number = Phone_Number;
            this.Email = Email;
            this.Cruise_ID = Cruise_ID;
            this.Number_of_rooms = Number_of_rooms;
            this.Room = Room;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CruiseBookingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CruiseBookingResponse", Namespace="http://tempuri.org/", Order=0)]
        public OnlineVacationReservation.ServiceReference4.CruiseBookingResponseBody Body;
        
        public CruiseBookingResponse() {
        }
        
        public CruiseBookingResponse(OnlineVacationReservation.ServiceReference4.CruiseBookingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CruiseBookingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CruiseBookingResult;
        
        public CruiseBookingResponseBody() {
        }
        
        public CruiseBookingResponseBody(int CruiseBookingResult) {
            this.CruiseBookingResult = CruiseBookingResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CruiseServiceSoapChannel : OnlineVacationReservation.ServiceReference4.CruiseServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CruiseServiceSoapClient : System.ServiceModel.ClientBase<OnlineVacationReservation.ServiceReference4.CruiseServiceSoap>, OnlineVacationReservation.ServiceReference4.CruiseServiceSoap {
        
        public CruiseServiceSoapClient() {
        }
        
        public CruiseServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CruiseServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CruiseServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CruiseServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnlineVacationReservation.ServiceReference4.CruiseBookingResponse OnlineVacationReservation.ServiceReference4.CruiseServiceSoap.CruiseBooking(OnlineVacationReservation.ServiceReference4.CruiseBookingRequest request) {
            return base.Channel.CruiseBooking(request);
        }
        
        public int CruiseBooking(string FirstName, string LastName, string Phone_Number, string Email, int Cruise_ID, int Number_of_rooms, string Room) {
            OnlineVacationReservation.ServiceReference4.CruiseBookingRequest inValue = new OnlineVacationReservation.ServiceReference4.CruiseBookingRequest();
            inValue.Body = new OnlineVacationReservation.ServiceReference4.CruiseBookingRequestBody();
            inValue.Body.FirstName = FirstName;
            inValue.Body.LastName = LastName;
            inValue.Body.Phone_Number = Phone_Number;
            inValue.Body.Email = Email;
            inValue.Body.Cruise_ID = Cruise_ID;
            inValue.Body.Number_of_rooms = Number_of_rooms;
            inValue.Body.Room = Room;
            OnlineVacationReservation.ServiceReference4.CruiseBookingResponse retVal = ((OnlineVacationReservation.ServiceReference4.CruiseServiceSoap)(this)).CruiseBooking(inValue);
            return retVal.Body.CruiseBookingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnlineVacationReservation.ServiceReference4.CruiseBookingResponse> OnlineVacationReservation.ServiceReference4.CruiseServiceSoap.CruiseBookingAsync(OnlineVacationReservation.ServiceReference4.CruiseBookingRequest request) {
            return base.Channel.CruiseBookingAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnlineVacationReservation.ServiceReference4.CruiseBookingResponse> CruiseBookingAsync(string FirstName, string LastName, string Phone_Number, string Email, int Cruise_ID, int Number_of_rooms, string Room) {
            OnlineVacationReservation.ServiceReference4.CruiseBookingRequest inValue = new OnlineVacationReservation.ServiceReference4.CruiseBookingRequest();
            inValue.Body = new OnlineVacationReservation.ServiceReference4.CruiseBookingRequestBody();
            inValue.Body.FirstName = FirstName;
            inValue.Body.LastName = LastName;
            inValue.Body.Phone_Number = Phone_Number;
            inValue.Body.Email = Email;
            inValue.Body.Cruise_ID = Cruise_ID;
            inValue.Body.Number_of_rooms = Number_of_rooms;
            inValue.Body.Room = Room;
            return ((OnlineVacationReservation.ServiceReference4.CruiseServiceSoap)(this)).CruiseBookingAsync(inValue);
        }
    }
}
